#!/bin/bash
#
# Sync Main to Develop Branch Script
#
# This script is used to merge changes from the main branch back into the develop branch.
# It prevents Git history divergence when using Squash merge and avoids conflicts on the next release.
#

set -e

# Global variables
MAIN_BRANCH=""
DEVELOP_BRANCH=""
AUTO_MERGE=""
SYNC_BRANCH=""
HAS_CONFLICTS=""

#
# Argument validation
#
validate_arguments() {
  if [ $# -ne 3 ]; then
    echo "Usage: $0 <main_branch> <develop_branch> <auto_merge>"
    echo "Example: $0 main develop true"
    exit 1
  fi

  MAIN_BRANCH="$1"
  DEVELOP_BRANCH="$2"
  AUTO_MERGE="$3"
}

#
# Show configuration
#
show_configuration() {
  echo "📋 Configuration:"
  echo "  Main branch: ${MAIN_BRANCH}"
  echo "  Develop branch: ${DEVELOP_BRANCH}"
  echo "  Auto merge: ${AUTO_MERGE}"
}

#
# Check whether the develop branch exists
#
check_develop_branch_exists() {
  if ! git ls-remote --heads origin "${DEVELOP_BRANCH}" | grep -q "${DEVELOP_BRANCH}"; then
    echo "⚠️  ${DEVELOP_BRANCH} branch does not exist. Skipping sync."
    exit 0
  fi
}

#
# Set up branches (fetch)
#
setup_branches() {
  echo "🔄 Fetching branches from origin"
  git fetch origin "${MAIN_BRANCH}:${MAIN_BRANCH}" --force
  git fetch origin "${DEVELOP_BRANCH}:${DEVELOP_BRANCH}" --force
}

#
# Check whether develop is up to date
# Return: 0=up to date, 1=not up to date
#
is_develop_up_to_date() {
  if git merge-base --is-ancestor "${MAIN_BRANCH}" "${DEVELOP_BRANCH}"; then
    echo "✅ ${DEVELOP_BRANCH} is already up-to-date with ${MAIN_BRANCH}"
    return 0
  fi
  return 1
}

#
# Create a sync branch
#
create_sync_branch() {
  SYNC_BRANCH="sync/${MAIN_BRANCH}-to-${DEVELOP_BRANCH}-$(date +%Y%m%d-%H%M%S)"

  echo "🔄 Creating sync branch: ${SYNC_BRANCH}"
  git checkout -b "${SYNC_BRANCH}" "origin/${DEVELOP_BRANCH}"
}

#
# Try merging main (conflict detection)
# Return: 0=success, 1=conflict
#
try_merge_main() {
  echo "🔀 Attempting to merge ${MAIN_BRANCH} into ${SYNC_BRANCH}"

  if git merge "origin/${MAIN_BRANCH}" --no-edit -m "Merge ${MAIN_BRANCH} into ${DEVELOP_BRANCH}"; then
    echo "✅ Merge successful (no conflicts)"
    HAS_CONFLICTS="false"
    return 0
  else
    echo "⚠️  Merge conflicts detected"
    HAS_CONFLICTS="true"
    # Reset conflicts
    git merge --abort
    # Recreate the branch (clean state)
    git checkout -b "${SYNC_BRANCH}" "origin/${DEVELOP_BRANCH}"
    return 1
  fi
}

#
# Push the sync branch
#
push_sync_branch() {
  echo "📤 Pushing ${SYNC_BRANCH} to origin"
  git push origin "${SYNC_BRANCH}"
}

#
# Create PR with conflicts
#
create_pr_with_conflicts() {
  echo "📝 Creating pull request (with conflicts)"

  local pr_body="## ⚠️ Merge conflicts detected

This PR was automatically created to sync changes from \`${MAIN_BRANCH}\` into \`${DEVELOP_BRANCH}\`.

### 🔴 Action required

Merge conflicts were detected. Resolve them with the steps below:

1. Check out this PR locally
2. Merge the \`${MAIN_BRANCH}\` branch
3. Resolve conflicts
4. Commit & push

\`\`\`bash
git fetch origin ${SYNC_BRANCH}
git checkout ${SYNC_BRANCH}
git merge origin/${MAIN_BRANCH}
# Resolve conflicts
git add .
git commit -m \"Resolve merge conflicts\"
git push origin ${SYNC_BRANCH}
\`\`\`

### 📋 Background

When you release from \`${DEVELOP_BRANCH}\` → \`${MAIN_BRANCH}\` using Squash merge, Git history diverges.
This merge-back prevents conflicts on the next release.

---
🤖 This PR was automatically generated by GitHub Actions"

  gh pr create \
    --base "${DEVELOP_BRANCH}" \
    --head "${SYNC_BRANCH}" \
    --title "🔄 Sync ${MAIN_BRANCH} to ${DEVELOP_BRANCH} (Conflicts Detected)" \
    --body "${pr_body}" \
    --label "sync" \
    --label "conflicts"

  echo "⚠️  PR created with conflicts. Manual resolution required."
}

#
# Create PR without conflicts
# Return: PR URL
#
create_pr_without_conflicts() {
  echo "📝 Creating pull request (no conflicts)"

  local pr_body="## ✅ Automatic Sync

This PR was automatically created to sync changes from \`${MAIN_BRANCH}\` into \`${DEVELOP_BRANCH}\`.

### 🎉 No conflicts

No merge conflicts were detected."

  if [ "${AUTO_MERGE}" = "true" ]; then
    pr_body="${pr_body}
This PR will be merged automatically."
  else
    pr_body="${pr_body}
Please review and merge manually."
  fi

  pr_body="${pr_body}

### 📋 Background

When you release from \`${DEVELOP_BRANCH}\` → \`${MAIN_BRANCH}\` using Squash merge, Git history diverges.
This merge-back prevents conflicts on the next release.

---
🤖 This PR was automatically generated by GitHub Actions"

  local pr_url
  pr_url=$(gh pr create \
    --base "${DEVELOP_BRANCH}" \
    --head "${SYNC_BRANCH}" \
    --title "🔄 Sync ${MAIN_BRANCH} to ${DEVELOP_BRANCH}" \
    --body "${pr_body}" \
    --label "sync")

  echo "✅ PR created: ${pr_url}"
  echo "${pr_url}"
}

#
# Auto-merge PR
#
auto_merge_pr() {
  local pr_url="$1"

  echo "🚀 Auto-merging PR"
  local pr_number
  pr_number=$(echo "${pr_url}" | grep -oE '[0-9]+$')

  # Wait briefly until the PR is fully created
  sleep 5

  # Perform merge
  gh pr merge "${pr_number}" \
    --merge \
    --delete-branch \
    --admin

  echo "✅ PR merged automatically"
}

#
# Main flow
#
main() {
  # 1. Validate arguments
  validate_arguments "$@"

  # 2. Show configuration
  show_configuration

  # 3. Check develop branch exists
  check_develop_branch_exists

  # 4. Set up branches
  setup_branches

  # 5. Check whether develop is up to date
  if is_develop_up_to_date; then
    exit 0
  fi

  # 6. Create sync branch
  create_sync_branch

  # 7. Try merging main
  try_merge_main

  # 8. Push sync branch
  push_sync_branch

  # 9. Create PR
  if [ "${HAS_CONFLICTS}" = "true" ]; then
    create_pr_with_conflicts
  else
    local pr_url
    pr_url=$(create_pr_without_conflicts)

    # 10. Auto merge
    if [ "${AUTO_MERGE}" = "true" ]; then
      auto_merge_pr "${pr_url}"
    fi
  fi
}

# Run script
main "$@"
